AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template to create a S3 Bucket'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: proydev
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        -
          Key: Project
          Value: CloudFormationLearning
          Key: Name
          Value: proydev

